In [1]:
#a

# Reading a CSV file
import pandas as pd

csv_df = pd.read_csv("/content/drive/MyDrive/ML_Assignments/datasets/admission.csv")
print("CSV file loaded successfully!")

CSV file loaded successfully!

In [2]:
#b

print("Shape of data (rows, columns):", csv_df.shape)

Shape of data (rows, columns): (500, 9)

In [3]:
#c

print("Missing values in each column:")
print(csv_df.isnull().sum())

Missing values in each column:
Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [4]:
#d
print("Data types of each column:")
print(csv_df.dtypes)

Data types of each column:
Serial No.             int64
GRE Score              int64
TOEFL Score            int64
University Rating      int64
SOP                  float64
LOR                  float64
CGPA                 float64
Research               int64
Chance of Admit      float64
dtype: object

In [5]:
#e
print("Number of zeroes in each column:")
print((csv_df == 0).sum())

Number of zeroes in each column:
Serial No.             0
GRE Score              0
TOEFL Score            0
University Rating      0
SOP                    0
LOR                    0
CGPA                   0
Research             220
Chance of Admit        0
dtype: int64

In [7]:
#f
# Selecting a specific column
print(csv_df['GRE Score'].head())

0    337
1    324
2    316
3    322
4    314
Name: GRE Score, dtype: int64

In [9]:
#f
# Selecting rows using index
csv_df.iloc[0:5] # First 5 rows

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65

In [10]:
#f
# Sorting by CGPA
sorted_df = csv_df.sort_values(by='CGPA', ascending=False)
print("Top 5 rows sorted by CGPA:")
sorted_df.head()

Top 5 rows sorted by CGPA:

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
143,144,340,120,4,4.5,4.0,9.92,1,0.97
202,203,340,120,5,4.5,4.5,9.91,1,0.97
203,204,334,120,5,4.0,5.0,9.87,1,0.97
496,497,337,117,5,5.0,5.0,9.87,1,0.96
425,426,323,111,5,4.0,5.0,9.86,1,0.92

In [11]:
#g
# Descriptive statistics
csv_df.describe()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.00000,500.000000,500.000000,500.00000
mean,250.500000,316.472000,107.192000,3.114000,3.374000,3.48400,8.576440,0.560000,0.72174
std,144.481833,11.295148,6.081868,1.143512,0.991004,0.92545,0.604813,0.496884,0.14114
min,1.000000,290.000000,92.000000,1.000000,1.000000,1.00000,6.800000,0.000000,0.34000
25%,125.750000,308.000000,103.000000,2.000000,2.500000,3.00000,8.127500,0.000000,0.63000
50%,250.500000,317.000000,107.000000,3.000000,3.500000,3.50000,8.560000,1.000000,0.72000
75%,375.250000,325.000000,112.000000,4.000000,4.000000,4.00000,9.040000,1.000000,0.82000
max,500.000000,340.000000,120.000000,5.000000,5.000000,5.00000,9.920000,1.000000,0.97000

In [12]:
#g
# Data types again
print("Data types of each column:\n")
csv_df.dtypes

Data types of each column:

Serial No.             int64
GRE Score              int64
TOEFL Score            int64
University Rating      int64
SOP                  float64
LOR                  float64
CGPA                 float64
Research               int64
Chance of Admit      float64
dtype: object

In [13]:
#h
# Counting unique values in each column
print("Unique values per column:")
print(csv_df.nunique())

Unique values per column:
Serial No.           500
GRE Score             49
TOEFL Score           29
University Rating      5
SOP                    9
LOR                    9
CGPA                 184
Research               2
Chance of Admit       61
dtype: int64

In [15]:
#h
# Convert float to int (e.g., GRE Score)
csv_df['GRE Score'] = csv_df['GRE Score'].astype(int)

In [17]:
#h
# Convert back to float
csv_df['GRE Score'] = csv_df['GRE Score'].astype(float)
print("Converted GRE Score column back and forth between int and float.")

Converted GRE Score column back and forth between int and float.

In [16]:
#h
# Check format of column (e.g. for float/int detection)
print("Column formats (float or int):")
print(csv_df.dtypes)

Column formats (float or int):
Serial No.             int64
GRE Score              int64
TOEFL Score            int64
University Rating      int64
SOP                  float64
LOR                  float64
CGPA                 float64
Research               int64
Chance of Admit      float64
dtype: object